Merged in ci_stablization (pull request #1240)
Ci stablization

* Merge branch 'master' of ssh://bitbucket.org/pabau/monorepo into ci_stablization

* chore: fresh yarn.lock

* aWW disabling e2e from failing pipeline again

* ci: don't use apt on cypress image

* ci: re-re-enable git checks for bridge:export

* ci: bridge:export one more time

* Merge branch 'master' of ssh://bitbucket.org/pabau/monorepo into ci_stablization

* Merge branch 'master' of ssh://bitbucket.org/pabau/monorepo into ci_stablization

* ci: bridge:export one more time

* ci: set lint to size: 4x


Approved-by: Ljubica Kostova
Approved-by: Alek Angelov
Approved-by: Nenad Jovanovski

diff --git a/bitbucket-pipelines.yml b/bitbucket-pipelines.yml
--- a/bitbucket-pipelines.yml
+++ b/bitbucket-pipelines.yml
@@ -22,12 +22,10 @@ pipelines:
           runs-on:
             - 'self.hosted'
           caches:
-            - nodemodules
             - yarncustom
           script:
-            #            - while true; do ps -aux && sleep 30; done &
             - /bin/bash -c 'yarn audit --no-progress --non-interactive; [[ $? -lt 16 ]] && exit 0 || exit 1'
-            - CYPRESS_CACHE_FOLDER=./dist/cypress CYPRESS_SKIP_BINARY_INSTALL=1 yarn install --frozen-lockfile --prefer-offline
+            - CYPRESS_SKIP_BINARY_INSTALL=1 yarn install --frozen-lockfile --prefer-offline
             - rm -f .postmon-lock
           artifacts:
             - node_modules/**
@@ -42,9 +40,12 @@ pipelines:
           script:
             #                - while true; do ps -aux && sleep 30; done &
             - NEXT_PUBLIC_GRAPHQL_ENDPOINT='https://api-v2-staging.pabau.com/v1/graphql' NEXT_PUBLIC_WS_ENDPOINT='wss://api-v2-staging.pabau.com/v1/graphql' yarn affected:export --base=origin/master --prod
+            - rm -rf dist/apps/**/.next/cache/
           artifacts:
             - dist/**
+
       - parallel:
+
           - step:
               name: deploy dockers
               size: 4x
@@ -152,12 +153,12 @@ pipelines:
               script:
                 #                - while true; do ps -aux && sleep 30; done &
                 - if git ls-files | git check-ignore --no-index --stdin; then echo "The above files are committed, but yet they are also in .gitignore. Don't mix."; fi
-                - rm -rf libs/graphql/crm-mutation apps/bridge-api/src/generated && yarn bridge:generate
-                - rm -rf libs/graphql/generated && yarn graphql-codegen
+                - rm -rf libs/graphql/crm-mutation apps/bridge-api/src/generated && yarn bridge:generate && git diff --exit-code --no-ext-diff -p
+                - rm -rf libs/graphql/generated && yarn graphql-codegen && git diff --exit-code --no-ext-diff -p
                 - yarn lint:tsc --base=origin/master
                 - yarn lint:ls || true
                 - yarn lint:workspace
-                # - yarn lint:graphql-inspector
+                - yarn lint:graphql-inspector || echo TODO
                 - yarn graphql-inspector coverage "{libs,apps}/**/*.{graphql,tsx}" hasura/schema.graphql || echo TODO
                 #                - graphql-inspector similar hasura/schema.graphql || echo TODO
                 - node_modules/.bin/ts-node tools/cli/check-duplicate-filenames.ts
@@ -166,6 +167,7 @@ pipelines:
 
           - step:
               name: lint
+              size: 4x
               runs-on:
                 - 'self.hosted'
               script:
@@ -189,11 +191,12 @@ pipelines:
               services:
                 - docker
               script:
-                - while true; do ps -aux && sleep 30; done &
+#                - while true; do ps -aux && sleep 30; done &
                 - |
                   echo "Testing Hasura database is consistent with schema.graphql..."
                   echo "============================================================"
                   echo ""
+                  printf "    extra_hosts:\n      - 'host.docker.internal:${BITBUCKET_DOCKER_HOST_INTERNAL}'\n" >> hasura/docker-compose.ci.yml
                   echo "Installing docker-compose..."
                   curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
                   chmod +x ~/docker-compose
@@ -216,15 +219,16 @@ pipelines:
                   yarn wait-on -t 60000 -d 10000 http-get://127.0.0.1:8080/console || echo "Still waiting for boot..."
                   yarn wait-on -t 60000 -d 10000 http-get://127.0.0.1:8080/console || (docker-compose -f hasura/docker-compose.ci.yml logs graphql-engine; exit 1)
                   HASURA_GRAPHQL_ENDPOINT="http://localhost:8080" yarn hasura:wait
-                # - |
-                #   echo "Checking Metadata is consistent so far..."
-                #   HASURA_GRAPHQL_ENDPOINT="http://localhost:8080" yarn hasura\li metadata inconsistency status
+                - |
+                  echo "Checking Metadata is consistent so far..."
+                  HASURA_GRAPHQL_ENDPOINT="http://localhost:8080" yarn hasura:cli metadata inconsistency status
                 - |
                   echo "Exporting Hasura metadata..."
                   HASURA_GRAPHQL_ENDPOINT="http://localhost:8080" yarn hasura:export
                 - |
                   echo "Ensuring everything is identical..."
-                # git diff --exit-code --no-ext-diff -p || (git status && exit 1)
+                  git checkout HEAD hasura/docker-compose.ci.yml
+                  git diff --exit-code --no-ext-diff -p || (git status && exit 1)
                 - |
                   echo "Waiting for MySQL to boot..."
                   docker-compose -f tools/pabau1/docker-compose.ci.yml up &
@@ -233,21 +237,28 @@ pipelines:
                   yarn wait-on -t 16000 -d 8000 tcp:localhost:3307 || echo "Still waiting for boot..."
                   yarn wait-on -t 16000 -d 8000 tcp:localhost:3307 || echo "Still waiting for boot..."
                   yarn wait-on -t 16000 -d 8000 tcp:localhost:3307 || (docker-compose -f tools/pabau1/docker-compose.ci.yml logs; exit 1)
-                # - |
-                #   echo "Performing load testing..."
-                #   yarn load-testing
+                - |
+                  echo "Performing load testing..."
+                  yarn load-testing
+
           - step:
               name: e2e
               size: 4x
+              image: cypress/browsers:node16.5.0-chrome94-ff93
               runs-on:
                 - 'self.hosted'
-              caches:
-                - cypress
               script:
-                #                - while true; do ps -aux && sleep 30; done &
-                - apt update -y && apt install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
-                - yarn cypress install || true
-                - yarn affected:e2e --base=origin/master || true
+                - while true; do ps -aux && sleep 30; done &
+                - yarn cypress install
+                - DEBUG=cypress:* yarn affected:e2e --base=origin/master --maxParallel=1 || echo "FAILED :("
+          - step:
+              name: e2e cloud
+              size: 2x
+              image: cypress/browsers:node16.5.0-chrome94-ff93
+              script:
+                - while true; do ps -aux && sleep 30; done &
+                - yarn cypress install
+                - DEBUG=cypress:* yarn affected:e2e --base=origin/master --maxParallel=1 || echo "FAILED :("
 
   branches:
     master:
@@ -281,7 +292,7 @@ pipelines:
                 - yarn lint:tsc --base=HEAD~1
                 - yarn lint:ls || true
                 - yarn lint:workspace
-                # - yarn lint:graphql-inspector
+                - yarn lint:graphql-inspector || echo TODO
                 - yarn graphql-inspector coverage "{libs,apps}/**/*.{graphql,tsx}" hasura/schema.graphql || echo TODO
                 #                - graphql-inspector similar hasura/schema.graphql || echo TODO
                 - node_modules/.bin/ts-node tools/cli/check-duplicate-filenames.ts
@@ -289,6 +300,7 @@ pipelines:
 
           - step:
               name: lint
+              size: 4x
               runs-on:
                 - 'self.hosted'
               script:
@@ -305,22 +317,10 @@ pipelines:
                 - yarn affected:test --base=HEAD~1
 
           - step:
-              name: e2e
-              size: 4x
-              runs-on:
-                - 'self.hosted'
-              caches:
-                - cypress
-              script:
-                #                - while true; do ps -aux && sleep 30; done &
-                - apt update -y && apt install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
-                - yarn cypress install || true
-                - yarn affected:e2e --base=HEAD~1 || true
-          - step:
               name: integration tests
-              size: 4x
               runs-on:
                 - 'self.hosted'
+              size: 4x
               services:
                 - docker
               script:
@@ -329,6 +329,7 @@ pipelines:
                   echo "Testing Hasura database is consistent with schema.graphql..."
                   echo "============================================================"
                   echo ""
+                  printf "    extra_hosts:\n      - 'host.docker.internal:${BITBUCKET_DOCKER_HOST_INTERNAL}'\n" >> hasura/docker-compose.ci.yml
                   echo "Installing docker-compose..."
                   curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
                   chmod +x ~/docker-compose
@@ -351,15 +352,16 @@ pipelines:
                   yarn wait-on -t 60000 -d 10000 http-get://127.0.0.1:8080/console || echo "Still waiting for boot..."
                   yarn wait-on -t 60000 -d 10000 http-get://127.0.0.1:8080/console || (docker-compose -f hasura/docker-compose.ci.yml logs graphql-engine; exit 1)
                   HASURA_GRAPHQL_ENDPOINT="http://localhost:8080" yarn hasura:wait
-                # - |
-                #   echo "Checking Metadata is consistent so far..."
-                #   HASURA_GRAPHQL_ENDPOINT="http://localhost:8080" yarn hasura:cli metadata inconsistency status
+                - |
+                  echo "Checking Metadata is consistent so far..."
+                  HASURA_GRAPHQL_ENDPOINT="http://localhost:8080" yarn hasura:cli metadata inconsistency status
                 - |
                   echo "Exporting Hasura metadata..."
                   HASURA_GRAPHQL_ENDPOINT="http://localhost:8080" yarn hasura:export
                 - |
                   echo "Ensuring everything is identical..."
-                #  git diff --exit-code --no-ext-diff -p || (git status && exit 1)
+                  git checkout HEAD hasura/docker-compose.ci.yml
+                  git diff --exit-code --no-ext-diff -p || (git status && exit 1)
                 - |
                   echo "Waiting for MySQL to boot..."
                   docker-compose -f tools/pabau1/docker-compose.ci.yml up &
@@ -368,9 +370,10 @@ pipelines:
                   yarn wait-on -t 16000 -d 8000 tcp:localhost:3307 || echo "Still waiting for boot..."
                   yarn wait-on -t 16000 -d 8000 tcp:localhost:3307 || echo "Still waiting for boot..."
                   yarn wait-on -t 16000 -d 8000 tcp:localhost:3307 || (docker-compose -f tools/pabau1/docker-compose.ci.yml logs; exit 1)
-                # - |
-                #   echo "Performing load testing..."
-                #   yarn load-testing
+                - |
+                  echo "Performing load testing..."
+                  yarn load-testing
+
       - step:
           name: bump version
           max-time: 5
@@ -394,6 +397,7 @@ pipelines:
           script:
             #            - while true; do ps -aux && sleep 30; done &
             - NEXT_PUBLIC_GRAPHQL_ENDPOINT='https://api-v2.pabau.com/v1/graphql' NEXT_PUBLIC_WS_ENDPOINT='wss://api-v2.pabau.com/v1/graphql' yarn affected:export --base=HEAD~1 --prod
+            - rm -rf dist/apps/**/.next/cache/
           artifacts:
             - dist/**
 
@@ -422,11 +426,6 @@ pipelines:
               deployment: production-serverless
               script:
                 #                - while true; do ps -aux && sleep 30; done &
-                - ls -al . || true
-                - ls -al node_modules/ || true
-                - ls -al dist || true
-                - ls -al dist/apps || true
-                - cat /tmp/bot_message.txt || true
                 - apt-get update -y && apt-get install -y curl jq time
 
                 # get the commit message for this merge
